package com.puntomartinez.millete.assistant.domain.model;

public enum AppAction {

    ADD_CATEGORY,
    EDIT_CATEGORY,

    ADD_EXPENSE_TRANSACTION,
    ADD_INCOME_TRANSACTION,
    EDIT_TRANSACTION,

    ADD_RECURRING_EXPENSE_TRANSACTION,
    ADD_RECURRING_INCOME_TRANSACTION,
    EDIT_RECURRING_TRANSACTION,

    ADD_SAVING_GOAL,
    EDIT_SAVING_GOAL,
    ADD_SAVING_GOAL_CONTRIBUTION
}