// scripts/migrate-keys.js
const fs = require('fs');
const path = require('path');

// Mapeo completo de claves antiguas -> nuevas
const migrationMap = {
  // ===== COMMON =====
  "common.save": "common:actions.save",
  "common.saving": "common:actions.saving",
  "common.cancel": "common:actions.cancel",
  "common.edit": "common:actions.edit",
  "common.delete": "common:actions.delete",
  "common.deleting": "common:actions.deleting",
  "common.add": "common:actions.add",
  "common.accept": "common:actions.accept",
  "common.reject": "common:actions.reject",
  "common.close": "common:actions.close",
  "common.search": "common:actions.search",
  "common.loading": "common:status.loading",
  "common.loadingSession": "common:status.loadingSession",
  "common.error": "common:status.error",
  "common.goToLogin": "common:status.goToLogin",

  // ===== NAV =====
  "nav.user": "nav:user",
  "nav.changeLanguage": "nav:changeLanguage",
  "nav.guest": "nav:guest",
  "nav.goToDashboard": "nav:goToDashboard",
  "nav.userMenu": "nav:userMenu",
  "nav.profile": "nav:profile",
  "nav.logout": "nav:logout",
  "nav.logoutSuccess": "nav:logoutSuccess",
  "nav.errors.languageChangeFailed": "nav:errors.languageChangeFailed",
  "theme.selector": "nav:theme.selector",
  "theme.palette": "nav:theme.palette",
  "theme.errors.themeChangeFailed": "nav:theme.errors.themeChangeFailed",
  "carousel.previous": "nav:carousel.previous",
  "carousel.next": "nav:carousel.next",
  "sidebar.mainNav": "nav:mainNav",
  "sidebar.bottomNav": "nav:bottomNav",
  "sidebar.open": "nav:open",
  "sidebar.close": "nav:close",
  "sidebar.noItems": "nav:noItems",
  "sidebar.comingSoon": "nav:comingSoon",
  "sidebar.dashboard": "nav:dashboard",
  "sidebar.transactions": "nav:transactions",
  "sidebar.categories": "nav:categories",
  "sidebar.investments": "nav:investments",
  "sidebar.groupgoals": "nav:groupgoals",
  "sidebar.savingsgoals": "nav:savingsgoals",
  "sidebar.mobileTitle": "nav:mobileTitle",
  "sidebar.settings": "nav:settings",
  "sidebar.errors.featureComingSoon": "nav:errors.featureComingSoon",

  // ===== AUTH =====
  "auth.brand.name": "auth:brand.name",
  "auth.brand.tagline": "auth:brand.tagline",
  "auth.greeting": "auth:greeting",
  "auth.footer.webVersion": "auth:footer.webVersion",
  "auth.footer.apiVersion": "auth:footer.apiVersion",
  "auth.footer.copyright": "auth:footer.copyright",
  "auth.form.optional": "auth:form.optional",
  "auth.form.andOr": "auth:form.andOr",
  "auth.form.registerHint": "auth:form.registerHint",
  "auth.form.passwordHint": "auth:form.passwordHint",
  "auth.form.toggle.login": "auth:form.toggle.login",
  "auth.form.toggle.register": "auth:form.toggle.register",
  "auth.form.fields.identifier.login": "auth:form.fields.identifier.login",
  "auth.form.fields.identifier.register": "auth:form.fields.identifier.register",
  "auth.form.fields.placeholder.login": "auth:form.fields.placeholder.login",
  "auth.form.fields.placeholder.register": "auth:form.fields.placeholder.register",
  "auth.form.fields.password.label": "auth:form.fields.password.label",
  "auth.form.fields.password.placeholder": "auth:form.fields.password.placeholder",
  "auth.form.fields.username.label": "auth:form.fields.username.label",
  "auth.form.fields.username.placeholder": "auth:form.fields.username.placeholder",
  "auth.form.forgotPassword": "auth:form.forgotPassword",
  "auth.form.error.invalidCredentials": "auth:errors.invalidCredentials",
  "auth.form.error.registerFailed": "auth:errors.registerFailed",
  "auth.form.error.required": "validations:required",
  "auth.submit.default": "auth:submit.default",
  "auth.submit.loading": "auth:submit.loading",
  "auth.submit.register": "auth:submit.register",
  "auth.forgotPassword.title": "auth:forgotPassword.title",
  "auth.forgotPassword.description": "auth:forgotPassword.description",
  "auth.forgotPassword.send": "auth:forgotPassword.send",
  "auth.forgotPassword.emailRequired": "validations:required",
  "auth.forgotPassword.emailInvalid": "validations:invalid_email",
  "auth.forgotPassword.sending": "auth:forgotPassword.sending",
  "auth.forgotPassword.sendingDescription": "auth:forgotPassword.sendingDescription",
  "auth.forgotPassword.success": "auth:forgotPassword.success",
  "auth.forgotPassword.successDescription": "auth:forgotPassword.successDescription",
  "auth.forgotPassword.error": "auth:forgotPassword.error",
  "auth.forgotPassword.errorDescription": "auth:forgotPassword.errorDescription",
  "auth.forgotPassword.tryAgain": "auth:forgotPassword.tryAgain",
  "auth.forgotPassword.cancel": "auth:forgotPassword.cancel",
  "auth.forgotPassword.backToLogin": "auth:forgotPassword.backToLogin",
  "auth.alerts.welcome_back": "auth:alerts.welcome_back",
  "auth.alerts.register_success": "auth:alerts.register_success",
  "auth.alerts.login_error_title": "auth:alerts.login_error_title",
  "auth.errors.no_identifier": "auth:errors.no_identifier",
  "auth.errors.auto_login_failed": "auth:errors.auto_login_failed",
  "auth.errors.register_failed": "auth:errors.register_failed",

  // ===== DASHBOARD =====
  "dashboard.metrics.balance": "dashboard:metrics.balance",
  "dashboard.metrics.income": "dashboard:metrics.income",
  "dashboard.metrics.expenses": "dashboard:metrics.expenses",
  "dashboard.metrics.savings": "dashboard:metrics.savings",
  "dashboard.metrics.vsLastWeek": "dashboard:metrics.vsLastWeek",
  "dashboard.metrics.vsLastMonth": "dashboard:metrics.vsLastMonth",
  "dashboard.metrics.vsLastYear": "dashboard:metrics.vsLastYear",
  "dashboard.metrics.errors.noDataAvailable": "dashboard:metrics.errors.noDataAvailable",
  "dashboard.header.greeting.morning": "dashboard:header.greeting.morning",
  "dashboard.header.greeting.afternoon": "dashboard:header.greeting.afternoon",
  "dashboard.header.greeting.evening": "dashboard:header.greeting.evening",
  "dashboard.header.separator": "dashboard:header.separator",
  "dashboard.header.dateFormat": "dashboard:header.dateFormat",
  "dashboard.header.week": "dashboard:header.week",
  "dashboard.header.period.ariaLabel": "dashboard:header.period.ariaLabel",
  "dashboard.header.period.week": "dashboard:header.period.week",
  "dashboard.header.period.month": "dashboard:header.period.month",
  "dashboard.header.period.year": "dashboard:header.period.year",
  "dashboard.chart.title": "dashboard:chart.title",
  "dashboard.chart.empty": "dashboard:chart.empty",
  "dashboard.chart.showingLast": "dashboard:chart.showingLast",
  "dashboard.chart.periodLabel.week": "dashboard:chart.periodLabel.week",
  "dashboard.chart.periodLabel.month": "dashboard:chart.periodLabel.month",
  "dashboard.chart.periodLabel.year": "dashboard:chart.periodLabel.year",
  "dashboard.chart.tooltip.amount": "dashboard:chart.tooltip.amount",
  "dashboard.chart.tooltip.percentage": "dashboard:chart.tooltip.percentage",
  "dashboard.donut.title": "dashboard:donut.title",
  "dashboard.donut.total": "dashboard:donut.total",
  "dashboard.donut.empty": "dashboard:donut.empty",
  "dashboard.budget.title": "dashboard:budget.title",
  "dashboard.budget.empty": "dashboard:budget.empty",
  "dashboard.budget.overLimit": "dashboard:budget.overLimit",
  "dashboard.budget.remaining": "dashboard:budget.remaining",
  "dashboard.budget.exceededBy": "dashboard:budget.exceededBy",
  "dashboard.transactions.title": "dashboard:transactions.title",
  "dashboard.transactions.viewAll": "dashboard:transactions.viewAll",
  "dashboard.transactions.empty": "dashboard:transactions.empty",
  "dashboard.transactions.expense": "dashboard:transactions.expense",
  "dashboard.transactions.income": "dashboard:transactions.income",
  "dashboard.transactions.moreOptions": "dashboard:transactions.moreOptions",
  "dashboard.goals.title": "dashboard:goals.title",
  "dashboard.goals.empty": "dashboard:goals.empty",
  "dashboard.goals.completed": "dashboard:goals.completed",
  "dashboard.goals.remaining": "dashboard:goals.remaining",
  "dashboard.quickActions.addExpense": "dashboard:quickActions.addExpense",
  "dashboard.quickActions.createCategory": "dashboard:quickActions.createCategory",
  "dashboard.quickActions.importData": "dashboard:quickActions.importData",
  "dashboard.quickActions.importing": "dashboard:quickActions.importing",
  "dashboard.quickActions.exportData": "dashboard:quickActions.exportData",
  "dashboard.quickActions.exporting": "dashboard:quickActions.exporting",
  "dashboard.quickActions.addExpenseAria": "dashboard:quickActions.addExpenseAria",
  "dashboard.quickActions.createCategoryAria": "dashboard:quickActions.createCategoryAria",
  "dashboard.quickActions.importDataAria": "dashboard:quickActions.importDataAria",
  "dashboard.quickActions.importingAria": "dashboard:quickActions.importingAria",
  "dashboard.quickActions.exportDataAria": "dashboard:quickActions.exportDataAria",
  "dashboard.quickActions.exportingAria": "dashboard:quickActions.exportingAria",
  "dashboard.quickActions.groupLabel": "dashboard:quickActions.groupLabel",
  "dashboard.importModal.title": "dashboard:importModal.title",
  "dashboard.importModal.description": "dashboard:importModal.description",
  "dashboard.importModal.dropHere": "dashboard:importModal.dropHere",
  "dashboard.importModal.onlyJson": "dashboard:importModal.onlyJson",
  "dashboard.importModal.jsonOnly": "dashboard:importModal.jsonOnly",
  "dashboard.importModal.invalidJson": "dashboard:importModal.invalidJson",
  "dashboard.importModal.importing": "dashboard:importModal.importing",
  "dashboard.importModal.success": "dashboard:importModal.success",
  "dashboard.importModal.importError": "dashboard:importModal.importError",
  "dashboard.importModal.close": "dashboard:importModal.close",
  "dashboard.import.success": "dashboard:import.success",
  "dashboard.import.errorGeneric": "dashboard:import.errorGeneric",
  "dashboard.import.errorProperty": "dashboard:import.errorProperty",
  "dashboard.import.errorFormat": "dashboard:import.errorFormat",
  "dashboard.export.success": "dashboard:export.success",
  "dashboard.export.error": "dashboard:export.error",

  // ===== TRANSACTIONS =====
  "transactions.title": "transactions:title",
  "transactions.description": "transactions:description",
  "transactions.descriptionPlaceholder": "transactions:descriptionPlaceholder",
  "transactions.type": "transactions:type",
  "transactions.expense": "transactions:expense",
  "transactions.income": "transactions:income",
  "transactions.amount": "transactions:amount",
  "transactions.category": "transactions:category",
  "transactions.selectCategory": "transactions:selectCategory",
  "transactions.noCategory": "transactions:noCategory",
  "transactions.search": "transactions:search",
  "transactions.empty": "transactions:empty",
  "transactions.showingInterval": "transactions:showingInterval",
  "transactions.createError": "transactions:createError",
  "transactions.filterAll": "transactions:filterAll",
  "transactions.filterIncome": "transactions:filterIncome",
  "transactions.filterExpense": "transactions:filterExpense",
  "transactions.add": "transactions:add",
  "transactions.save": "transactions:save",
  "transactions.edit": "transactions:edit",
  "transactions.editTitle": "transactions:editTitle",
  "transactions.delete": "transactions:delete",
  "transactions.deleteConfirm": "transactions:deleteConfirm",
  "transactions.new": "transactions:new",
  "transactions.newShort": "transactions:newShort",
  "transactions.newTitle": "transactions:newTitle",
  "transactions.moreOptions": "transactions:moreOptions",
  "transactions.deleteTitle": "transactions:deleteTitle",
  "transactions.deleteConfirmation": "transactions:deleteConfirmation",
  "transactions.recurring.deleteTitle": "transactions:recurring.deleteTitle",
  "transactions.recurring.deleteConfirmation": "transactions:recurring.deleteConfirmation",
  "transactions.recurring.label": "transactions:recurring.label",
  "transactions.recurring.shortLabel": "transactions:recurring.shortLabel",
  "transactions.recurring.newTitle": "transactions:recurring.newTitle",
  "transactions.recurring.editTitle": "transactions:recurring.editTitle",
  "transactions.recurring.listTitle": "transactions:recurring.listTitle",
  "transactions.recurring.emptyFilter": "transactions:recurring.emptyFilter",
  "transactions.recurring.frequency": "transactions:recurring.frequency",
  "transactions.recurring.selectFrequency": "transactions:recurring.selectFrequency",
  "transactions.recurring.interval": "transactions:recurring.interval",
  "transactions.recurring.startDate": "transactions:recurring.startDate",
  "transactions.recurring.endDate": "transactions:recurring.endDate",
  "transactions.recurring.days": "transactions:recurring.days",
  "transactions.recurring.weeks": "transactions:recurring.weeks",
  "transactions.recurring.months": "transactions:recurring.months",
  "transactions.recurring.years": "transactions:recurring.years",
  "transactions.recurring.everyDay": "transactions:recurring.everyDay",
  "transactions.recurring.everyWeek": "transactions:recurring.everyWeek",
  "transactions.recurring.everyMonth": "transactions:recurring.everyMonth",
  "transactions.recurring.everyYear": "transactions:recurring.everyYear",
  "transactions.recurring.every": "transactions:recurring.every",
  "transactions.recurring.indefinite": "transactions:recurring.indefinite",
  "transactions.recurring.nextExecution": "transactions:recurring.nextExecution",
  "transactions.recurring.summary": "transactions:recurring.summary",
  "transactions.recurring.summaryText": "transactions:recurring.summaryText",
  "transactions.recurring.units.days": "transactions:recurring.units.days",
  "transactions.recurring.units.weeks": "transactions:recurring.units.weeks",
  "transactions.recurring.units.months": "transactions:recurring.units.months",
  "transactions.recurring.units.years": "transactions:recurring.units.years",
  "transactions.alerts.createSuccess": "transactions:alerts.createSuccess",
  "transactions.alerts.updateSuccess": "transactions:alerts.updateSuccess",
  "transactions.alerts.deleteSuccess": "transactions:alerts.deleteSuccess",
  "transactions.alerts.createRecurringSuccess": "transactions:alerts.createRecurringSuccess",
  "transactions.alerts.updateRecurringSuccess": "transactions:alerts.updateRecurringSuccess",
  "transactions.alerts.deleteRecurringSuccess": "transactions:alerts.deleteRecurringSuccess",

  // ===== CATEGORIES =====
  "categories.add": "categories:add",
  "categories.newTitle": "categories:newTitle",
  "categories.editTitle": "categories:editTitle",
  "categories.name": "categories:name",
  "categories.namePlaceholder": "categories:namePlaceholder",
  "categories.color": "categories:color",
  "categories.budget": "categories:budget",
  "categories.budgetHint": "categories:budgetHint",
  "categories.currentBudget": "categories:currentBudget",
  "categories.family": "categories:family",
  "categories.selectFamilyPlaceholder": "categories:selectFamilyPlaceholder",
  "categories.selectFamily": "categories:selectFamily",
  "categories.noFamily": "categories:noFamily",
  "categories.noFamilies": "categories:noFamilies",
  "categories.familyTitle": "categories:familyTitle",
  "categories.assign": "categories:assign",
  "categories.search": "categories:search",
  "categories.showing": "categories:showing",
  "categories.empty": "categories:empty",
  "categories.save": "categories:save",
  "categories.edit": "categories:edit",
  "categories.delete": "categories:delete",
  "categories.createError": "categories:createError",
  "categories.updateError": "categories:updateError",
  "categories.deleteTitle": "categories:deleteTitle",
  "categories.deleteConfirmation": "categories:deleteConfirmation",
  "categories.deleteError": "categories:deleteError",
  "categories.noBudgetTooltip": "categories:noBudgetTooltip",
  "categories.createSuccess": "categories:createSuccess",
  "categories.updateSuccess": "categories:updateSuccess",
  "categories.deleteSuccess": "categories:deleteSuccess",
  "categories.nameRequired": "categories:nameRequired",
  "categories.invalidBudget": "categories:invalidBudget",
  "categories.editDescription": "categories:editDescription",
  "categories.nameLabel": "categories:nameLabel",
  "categories.budgetLabel": "categories:budgetLabel",
  "categories.budgetPlaceholder": "categories:budgetPlaceholder",
  "categories.colorLabel": "categories:colorLabel",

  // ===== INVESTMENTS =====
  "investments.title": "investments:title",
  "investments.portfolioValue": "investments:portfolioValue",
  "investments.monthlyReturn": "investments:monthlyReturn",
  "investments.dividends": "investments:dividends",
  "investments.comingSoon": "investments:comingSoon",
  "investments.evolution": "investments:evolution",
  "investments.lastMonths": "investments:lastMonths",
  "investments.distribution": "investments:distribution",
  "investments.total": "investments:total",
  "investments.myAssets": "investments:myAssets",
  "investments.searchAsset": "investments:searchAsset",
  "investments.noAssets": "investments:noAssets",
  "investments.shares": "investments:shares",
  "investments.filterAll": "investments:filterAll",
  "investments.new": "investments:new",
  "investments.newTitle": "investments:newTitle",
  "investments.assetName": "investments:assetName",
  "investments.assetNamePlaceholder": "investments:assetNamePlaceholder",
  "investments.ticker": "investments:ticker",
  "investments.type": "investments:type",
  "investments.quantity": "investments:quantity",
  "investments.purchasePrice": "investments:purchasePrice",
  "investments.purchaseDate": "investments:purchaseDate",
  "investments.save": "investments:save",
  "investments.updatePrice": "investments:updatePrice",
  "investments.marketPrice": "investments:marketPrice",
  "investments.newPrice": "investments:newPrice",
  "investments.updateNow": "investments:updateNow",
  "investments.delete": "investments:delete",
  "investments.deleteConfirm": "investments:deleteConfirm",
  "investments.createError": "investments:createError",
  "investments.assetOptions": "investments:assetOptions",
  "investments.deleteTitle": "investments:deleteTitle",
  "investments.deleteConfirmation": "investments:deleteConfirmation",
  "investments.types.stock": "investments:types.stock",
  "investments.types.crypto": "investments:types.crypto",
  "investments.types.fund": "investments:types.fund",
  "investments.types.realEstate": "investments:types.realEstate",
  "investments.types.real_estate": "investments:types.real_estate",
  "investments.types.other": "investments:types.other",
  "investments.alerts.createSuccess": "investments:alerts.createSuccess",
  "investments.alerts.updatePriceSuccess": "investments:alerts.updatePriceSuccess",
  "investments.alerts.deleteSuccess": "investments:alerts.deleteSuccess",
  "investments.alerts.warningTitle": "investments:alerts.warningTitle",
  "investments.alerts.warningDesc": "investments:alerts.warningDesc",
  "investments.confirmUpdate": "investments:confirmUpdate",
  "investments.updatePriceError": "investments:updatePriceError",
  "investments.charts.tooltip.amount": "investments:charts.tooltip.amount",
  "investments.charts.tooltip.percentage": "investments:charts.tooltip.percentage",
  "investments.charts.tooltip.wealth": "investments:charts.tooltip.wealth",

  // ===== GROUPGOALS =====
  "groupGoals.title": "groupGoals:title",
  "groupGoals.selectOrCreate": "groupGoals:selectOrCreate",
  "groupGoals.noFamilies": "groupGoals:noFamilies",
  "groupGoals.createFirst": "groupGoals:createFirst",
  "groupGoals.createNew": "groupGoals:createNew",
  "groupGoals.create": "groupGoals:create",
  "groupGoals.redirectingToLogin": "groupGoals:redirectingToLogin",
  "groupGoals.createTitle": "groupGoals:createTitle",
  "groupGoals.createDesc": "groupGoals:createDesc",
  "groupGoals.familyName": "groupGoals:familyName",
  "groupGoals.familyNamePlaceholder": "groupGoals:familyNamePlaceholder",
  "groupGoals.monthlyGoal": "groupGoals:monthlyGoal",
  "groupGoals.goal": "groupGoals:goal",
  "groupGoals.admin": "groupGoals:admin",
  "groupGoals.invitationReceived": "groupGoals:invitationReceived",
  "groupGoals.invitationMessage": "groupGoals:invitationMessage",
  "groupGoals.member": "groupGoals:member",
  "groupGoals.members": "groupGoals:members",
  "groupGoals.people": "groupGoals:people",
  "groupGoals.inviteMember": "groupGoals:inviteMember",
  "groupGoals.inviteShort": "groupGoals:inviteShort",
  "groupGoals.inviteTitle": "groupGoals:inviteTitle",
  "groupGoals.inviteDesc": "groupGoals:inviteDesc",
  "groupGoals.email": "groupGoals:email",
  "groupGoals.emailPlaceholder": "groupGoals:emailPlaceholder",
  "groupGoals.sendInvitation": "groupGoals:sendInvitation",
  "groupGoals.invalidEmail": "groupGoals:invalidEmail",
  "groupGoals.changeGoal": "groupGoals:changeGoal",
  "groupGoals.goalShort": "groupGoals:goalShort",
  "groupGoals.changeGoalTitle": "groupGoals:changeGoalTitle",
  "groupGoals.changeGoalDesc": "groupGoals:changeGoalDesc",
  "groupGoals.goalProgress": "groupGoals:goalProgress",
  "groupGoals.goalProgressDesc": "groupGoals:goalProgressDesc",
  "groupGoals.collected": "groupGoals:collected",
  "groupGoals.of": "groupGoals:of",
  "groupGoals.mode": "groupGoals:mode",
  "groupGoals.distribution": "groupGoals:distribution",
  "groupGoals.distributionDesc": "groupGoals:distributionDesc",
  "groupGoals.distributionMode": "groupGoals:distributionMode",
  "groupGoals.progressBar.label": "groupGoals:progressBar.label",
  "groupGoals.progressBar.of": "groupGoals:progressBar.of",
  "groupGoals.modes.equitative": "groupGoals:modes.equitative",
  "groupGoals.modes.equitativeDesc": "groupGoals:modes.equitativeDesc",
  "groupGoals.modes.proportional": "groupGoals:modes.proportional",
  "groupGoals.modes.proportionalDesc": "groupGoals:modes.proportionalDesc",
  "groupGoals.modes.custom": "groupGoals:modes.custom",
  "groupGoals.modes.customDesc": "groupGoals:modes.customDesc",
  "groupGoals.memberDetails": "groupGoals:memberDetails",
  "groupGoals.memberOptions": "groupGoals:memberOptions",
  "groupGoals.memberProgress": "groupGoals:memberProgress",
  "groupGoals.contributions": "groupGoals:contributions",
  "groupGoals.contributionsHistory": "groupGoals:contributionsHistory",
  "groupGoals.noContributions": "groupGoals:noContributions",
  "groupGoals.addContribution": "groupGoals:addContribution",
  "groupGoals.addContributionShort": "groupGoals:addContributionShort",
  "groupGoals.amount": "groupGoals:amount",
  "groupGoals.save": "groupGoals:save",
  "groupGoals.salary": "groupGoals:salary",
  "groupGoals.monthlySalary": "groupGoals:monthlySalary",
  "groupGoals.toContribute": "groupGoals:toContribute",
  "groupGoals.contributed": "groupGoals:contributed",
  "groupGoals.contribution": "groupGoals:contribution",
  "groupGoals.date": "groupGoals:date",
  "groupGoals.nextPayment": "groupGoals:nextPayment",
  "groupGoals.inDays": "groupGoals:inDays",
  "groupGoals.name": "groupGoals:name",
  "groupGoals.role": "groupGoals:role",
  "groupGoals.edit": "groupGoals:edit",
  "groupGoals.editMember": "groupGoals:editMember",
  "groupGoals.delete": "groupGoals:delete",
  "groupGoals.deleteGoal": "groupGoals:deleteGoal",
  "groupGoals.deleteGoalConfirmation": "groupGoals:deleteGoalConfirmation",
  "groupGoals.customPercentage": "groupGoals:customPercentage",
  "groupGoals.customPercentageHint": "groupGoals:customPercentageHint",
  "groupGoals.customPercentageOk": "groupGoals:customPercentageOk",
  "groupGoals.invitationFrom": "groupGoals:invitationFrom",
  "groupGoals.invalidToken": "groupGoals:invalidToken",
  "groupGoals.invitationAccepted": "groupGoals:invitationAccepted",
  "groupGoals.invitationError": "groupGoals:invitationError",
  "groupGoals.processingInvitation": "groupGoals:processingInvitation",
  "groupGoals.welcome": "groupGoals:welcome",
  "groupGoals.goToFamily": "groupGoals:goToFamily",
  "groupGoals.error": "groupGoals:error",
  "groupGoals.back": "groupGoals:back",
  "groupGoals.selectFamily": "groupGoals:selectFamily",
  "groupGoals.alerts.createSuccess": "groupGoals:alerts.createSuccess",
  "groupGoals.alerts.createError": "groupGoals:alerts.createError",
  "groupGoals.alerts.inviteSuccess": "groupGoals:alerts.inviteSuccess",
  "groupGoals.alerts.inviteError": "groupGoals:alerts.inviteError",
  "groupGoals.alerts.modeSuccess": "groupGoals:alerts.modeSuccess",
  "groupGoals.alerts.modeError": "groupGoals:alerts.modeError",
  "groupGoals.alerts.goalSuccess": "groupGoals:alerts.goalSuccess",
  "groupGoals.alerts.goalError": "groupGoals:alerts.goalError",
  "groupGoals.alerts.deleteSuccess": "groupGoals:alerts.deleteSuccess",
  "groupGoals.alerts.deleteError": "groupGoals:alerts.deleteError",
  "groupGoals.alerts.memberEditSuccess": "groupGoals:alerts.memberEditSuccess",
  "groupGoals.alerts.memberEditError": "groupGoals:alerts.memberEditError",
  "groupGoals.alerts.memberDeleteSuccess": "groupGoals:alerts.memberDeleteSuccess",
  "groupGoals.alerts.memberDeleteError": "groupGoals:alerts.memberDeleteError",
  "groupGoals.alerts.contributionSuccess": "groupGoals:alerts.contributionSuccess",
  "groupGoals.alerts.contributionError": "groupGoals:alerts.contributionError",

  // ===== SAVINGSGOALS =====
  "savingsGoals.title": "savingsGoals:title",
  "savingsGoals.newGoal": "savingsGoals:newGoal",
  "savingsGoals.newGoalTitle": "savingsGoals:newGoalTitle",
  "savingsGoals.editGoalTitle": "savingsGoals:editGoalTitle",
  "savingsGoals.deleteGoalTitle": "savingsGoals:deleteGoalTitle",
  "savingsGoals.deleteGoalConfirmation": "savingsGoals:deleteGoalConfirmation",
  "savingsGoals.searchPlaceholder": "savingsGoals:searchPlaceholder",
  "savingsGoals.clearSearch": "savingsGoals:clearSearch",
  "savingsGoals.loadingError": "savingsGoals:loadingError",
  "savingsGoals.loadingDetails": "savingsGoals:loadingDetails",
  "savingsGoals.emptyState": "savingsGoals:emptyState",
  "savingsGoals.name": "savingsGoals:name",
  "savingsGoals.namePlaceholder": "savingsGoals:namePlaceholder",
  "savingsGoals.targetAmount": "savingsGoals:targetAmount",
  "savingsGoals.priority": "savingsGoals:priority",
  "savingsGoals.deadline": "savingsGoals:deadline",
  "savingsGoals.link": "savingsGoals:link",
  "savingsGoals.linkPlaceholder": "savingsGoals:linkPlaceholder",
  "savingsGoals.progress": "savingsGoals:progress",
  "savingsGoals.of": "savingsGoals:of",
  "savingsGoals.addFunds": "savingsGoals:addFunds",
  "savingsGoals.amount": "savingsGoals:amount",
  "savingsGoals.add": "savingsGoals:add",
  "savingsGoals.create": "savingsGoals:create",
  "savingsGoals.saveChanges": "savingsGoals:saveChanges",
  "savingsGoals.editGoal": "savingsGoals:editGoal",
  "savingsGoals.deleteGoal": "savingsGoals:deleteGoal",
  "savingsGoals.addContribution": "savingsGoals:addContribution",
  "savingsGoals.priorities.HIGH": "savingsGoals:priorities.HIGH",
  "savingsGoals.priorities.MEDIUM": "savingsGoals:priorities.MEDIUM",
  "savingsGoals.priorities.LOW": "savingsGoals:priorities.LOW",
  "savingsGoals.alerts.createSuccess": "savingsGoals:alerts.createSuccess",
  "savingsGoals.alerts.createError": "savingsGoals:alerts.createError",
  "savingsGoals.alerts.updateSuccess": "savingsGoals:alerts.updateSuccess",
  "savingsGoals.alerts.updateError": "savingsGoals:alerts.updateError",
  "savingsGoals.alerts.deleteSuccess": "savingsGoals:alerts.deleteSuccess",
  "savingsGoals.alerts.deleteError": "savingsGoals:alerts.deleteError",
  "savingsGoals.alerts.contributionSuccess": "savingsGoals:alerts.contributionSuccess",
  "savingsGoals.alerts.contributionError": "savingsGoals:alerts.contributionError",

  // ===== SETTINGS =====
  "settings.general.title": "settings:general.title",
  "settings.general.description": "settings:general.description",
  "settings.currency.title": "settings:currency.title",
  "settings.currency.description": "settings:currency.description",
  "settings.currency.placeholder": "settings:currency.placeholder",
  "settings.telegram.title": "settings:telegram.title",
  "settings.telegram.description": "settings:telegram.description",
  "settings.telegram.connected": "settings:telegram.connected",
  "settings.telegram.since": "settings:telegram.since",
  "settings.telegram.status.connected": "settings:telegram.status.connected",
  "settings.telegram.status.disconnected": "settings:telegram.status.disconnected",
  "settings.telegram.status.loading": "settings:telegram.status.loading",
  "settings.telegram.status.error": "settings:telegram.status.error",
  "settings.telegram.refresh": "settings:telegram.refresh",

  // ===== API =====
  "api.errors.default": "api:errors.default",
  "api.errors.status_401": "api:errors.status_401",
  "api.errors.status_403": "api:errors.status_403",
  "api.errors.status_404": "api:errors.status_404",
  "api.errors.status_500": "api:errors.status_500",
  "api.errors.timeout": "api:errors.timeout",
};

function migrateFile(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');
  let updated = false;

  for (const [oldKey, newKey] of Object.entries(migrationMap)) {
    // Reemplazar t('oldKey') y t("oldKey")
    const regex = new RegExp(`t\\(['"]${oldKey}['"]\\)`, 'g');
    if (content.includes(`t('${oldKey}')`) || content.includes(`t("${oldKey}")`)) {
      content = content.replace(regex, `t('${newKey}')`);
      updated = true;
    }
  }

  if (updated) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`✅ Migrated: ${path.relative(process.cwd(), filePath)}`);
  }
}

function walkDirectory(dir) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      walkDirectory(filePath);
    } else if (filePath.endsWith('.tsx') || filePath.endsWith('.ts')) {
      migrateFile(filePath);
    }
  }
}

// Ejecutar desde la raíz del proyecto
const srcDir = path.join(__dirname, '../src');
console.log('🚀 Iniciando migración de claves de traducción...');
walkDirectory(srcDir);
console.log('✅ Migración completada!');