# =========================================================================
# CONFIGURACIÓN PARA DESARROLLO LOCAL (IntelliJ)
# =========================================================================
server:
  port: 8080

spring:
  application:
    name: Millete
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/millete_db
    username: postgres
    password: 654321
    driver-class-name: org.postgresql.Driver

app:
  version: 0.1.2
  frontend:
    url: http://localhost:3000

jwt:
  secret: U3VwZXJTZWNy5XRfSldUX0tleV9Gb3JfVGVzdGluZ187MDI2X01pbGxldGUK
  expiration: 43200000
  cookie-name: ms_token
  cookie-secure: false          # true en producción (requiere HTTPS)
  cookie-http-only: true
  cookie-same-site: Strict
  cookie-path: /
  cookie-max-age: 43200         # 12 horas en segundos

logging:
  level:
    root: INFO
    com.puntomartinez: DEBUG